version: '3'

services:
  app:
    build: .
    volumes:
      - ./logs:/var/log/app
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DAILY_RUN_TIME=05:45
      - DEEPSEEK_API_KEY=<deepseek_api_key>
      - SC_KEY=<sc_key>
      - DB_PATH=/data/arxiv.db
      - SUMMARY_PATH=/data/paper_summary/